### ISSUE TITLE
Allow user to specify what resource pack to use

### ISSUE THREAD

**Issue by h3oCharles** [deirn/resource-backports#1]
hey there, what if i want to convert a resource pack that i already downloaded? like newer versions of Faithful that has textures based on JAPPA's textures, what if i want to convert that resource pack?

**Comment by deirn** [comment]
hi, sure, i think it easy enough to implement that

**Comment by deirn** [comment]
it's working now!
tested with faithful for **1.14**
mind you, it only copies the textures and not any model
you also need to actually use the 1.14 pack alongside the converted one
![20200626152224](https://user-images.githubusercontent.com/21150434/85836497-da29d580-b7c0-11ea-905d-092592bd4b86.png)
