### ISSUE TITLE
specify compiling instructions

### ISSUE THREAD

**Issue by h3oCharles** [deirn/resource-backports#2]
hey there,
i would like to get the changes in #1 but there's no release, so i wanted to compile it myself but uuh no compiling instructions? what version(s) of python do you use to compile this?

**Comment by deirn** [comment]
if you have python3 installed you just need to run it with `py script.py`
the one dependency that may not already be installed is requests
I wanted to publish the binary release but I somehow couldn't compile it...

**Comment by h3oCharles** [comment]
well i think i found it
![image](https://user-images.githubusercontent.com/8020330/86273950-4184c280-bbd1-11ea-8a32-3210081a1d43.png)







oh, wait, i don't have "requests" dependency uuh awkward... how does one get that "requests" thing on Windows?

![image](https://user-images.githubusercontent.com/8020330/86274392-e99a8b80-bbd1-11ea-97be-03d84d44139a.png)

i uuh err uuh i have no idea what im doing

**Comment by deirn** [comment]
@KarBoy2314PL 
figured out what's wrong and published binary, sorry for the inconvenience!
also if you still want to run it directly
```
py -m pip install requests
py -m pip install pillow
py resource_backports.py
```
