### ISSUE TITLE
OptiFine support?

### ISSUE THREAD

**Issue by Metadorius** [deirn/resource-backports#3]
I quickly skimmed through the code and didn't find any mentions of OptiFine's support. For as far as I know, OptiFine packs also need their structure to be edited to successfully be backported to older versions. Asking mainly because there is a very beautiful [Stay True pack](https://www.curseforge.com/minecraft/texture-packs/stay-true) which I would like to backport to my private 1.12.2 modpack.

**Comment by deirn** [comment]
no, sorry. this script supposed to be a one-time, simple script targeted for vanilla

**Comment by Metadorius** [comment]
Would you accept a pull request if I were to implement it?

**Comment by deirn** [comment]
Sure, i guess. I'll gladly accept your pr

**Comment by h3oCharles** [comment]
ik this is a closed issue, but i'll just mention this: most of the time renaming the folder "mcpatcher" to "optifine" (or vice-versa) fixes most of the problems

**Comment by Metadorius** [comment]
> ik this is a closed issue, but i'll just mention this: most of the time renaming the folder "mcpatcher" to "optifine" (or vice-versa) fixes most of the problems

This is not the case. Additionally to that one also needs to rename all block name references to their pre-flattening equivalents.
